use super::provider::{
    LocalizedDoc, MaxTlsVersion, OAuthConfig, Provider, ProviderEncryption, ServerConfig,
    UsernameType,
};

/// Helper to create a provider entry with common defaults.
#[allow(clippy::too_many_arguments)]
fn p(
    id: &str,
    display_name: &str,
    domains: &[&str],
    mx: &[&str],
    imap_host: &str,
    imap_port: u16,
    imap_enc: ProviderEncryption,
    smtp_host: &str,
    smtp_port: u16,
    smtp_enc: ProviderEncryption,
    username_type: UsernameType,
    keep_alive: u32,
    noop: bool,
    partial_fetch: bool,
    max_tls: MaxTlsVersion,
    app_password: bool,
    doc_url: Option<&str>,
    oauth: Option<OAuthConfig>,
    order: u32,
) -> Provider {
    Provider {
        id: id.to_string(),
        display_name: display_name.to_string(),
        domain_patterns: domains.iter().map(|s| s.to_string()).collect(),
        mx_patterns: mx.iter().map(|s| s.to_string()).collect(),
        incoming: ServerConfig {
            hostname: imap_host.to_string(),
            port: imap_port,
            encryption: imap_enc,
        },
        outgoing: ServerConfig {
            hostname: smtp_host.to_string(),
            port: smtp_port,
            encryption: smtp_enc,
        },
        username_type,
        keep_alive_interval: keep_alive,
        noop_keep_alive: noop,
        partial_fetch,
        max_tls_version: max_tls,
        app_password_required: app_password,
        documentation_url: doc_url.map(|s| s.to_string()),
        localized_docs: vec![],
        oauth,
        display_order: order,
        enabled: true,
        supports_shared_mailbox: false,
    }
}

/// Shorthand for SSL/TLS provider with email-as-username (most common pattern).
fn ssl_provider(
    id: &str,
    name: &str,
    domains: &[&str],
    imap_host: &str,
    smtp_host: &str,
    order: u32,
) -> Provider {
    p(
        id,
        name,
        domains,
        &[],
        imap_host,
        993,
        ProviderEncryption::SslTls,
        smtp_host,
        465,
        ProviderEncryption::SslTls,
        UsernameType::EmailAddress,
        15,
        false,
        true,
        MaxTlsVersion::Tls1_3,
        false,
        None,
        None,
        order,
    )
}

/// Returns all bundled provider entries.
pub(crate) fn bundled_providers() -> Vec<Provider> {
    let e = UsernameType::EmailAddress;
    let ssl = ProviderEncryption::SslTls;
    let starttls = ProviderEncryption::StartTls;
    let tls13 = MaxTlsVersion::Tls1_3;
    let tls12 = MaxTlsVersion::Tls1_2;

    vec![
        // === Top 20 global providers ===
        // 1. Gmail / Google
        {
            let mut prov = p(
                "gmail",
                "Gmail (Google)",
                &["gmail.com", "googlemail.com", "google.com"],
                &["*.google.com", "*.googlemail.com"],
                "imap.gmail.com",
                993,
                ssl,
                "smtp.gmail.com",
                465,
                ssl,
                e,
                15,
                false,
                true,
                tls13,
                true,
                Some("https://support.google.com/mail/answer/7126229"),
                Some(OAuthConfig {
                    auth_url: "https://accounts.google.com/o/oauth2/v2/auth".to_string(),
                    token_url: "https://oauth2.googleapis.com/token".to_string(),
                    redirect_uri: "http://127.0.0.1/callback".to_string(),
                    scopes: vec!["https://mail.google.com/".to_string()],
                    client_id: None,
                    extra_params: vec![
                        ("prompt".to_string(), "consent".to_string()),
                        ("access_type".to_string(), "offline".to_string()),
                    ],
                    userinfo_url: None,
                }),
                1,
            );
            prov.localized_docs.push(LocalizedDoc {
                locale: "en".to_string(),
                text: "Enable IMAP in Gmail settings. Use an App Password if 2FA is enabled."
                    .to_string(),
            });
            prov
        },
        // 2. Microsoft Outlook / Hotmail / Live
        {
            let mut prov = p(
                "outlook",
                "Outlook.com (Microsoft)",
                &["outlook.com", "hotmail.com", "live.com", "msn.com", "hotmail.co.uk", "hotmail.fr", "hotmail.de", "hotmail.it", "hotmail.es", "live.co.uk", "live.fr", "outlook.de", "outlook.fr", "outlook.co.uk"],
                &["*.outlook.com"],
                "outlook.office365.com", 993, ssl,
                "smtp.office365.com", 587, starttls,
                e, 15, false, true, tls13, false,
                Some("https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353"),
                Some(OAuthConfig {
                    auth_url: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize".to_string(),
                    token_url: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token".to_string(),
                    redirect_uri: "http://127.0.0.1/callback".to_string(),
                    scopes: vec!["https://outlook.office365.com/IMAP.AccessAsUser.All".to_string(), "https://outlook.office365.com/SMTP.Send".to_string(), "offline_access".to_string()],
                    client_id: None,
                    extra_params: vec![
                        ("prompt".to_string(), "consent".to_string()),
                    ],
                    userinfo_url: None,
                }),
                2,
            );
            prov.localized_docs.push(LocalizedDoc {
                locale: "en".to_string(),
                text: "Microsoft requires OAuth2 for Outlook.com accounts.".to_string(),
            });
            prov.supports_shared_mailbox = true;
            prov
        },
        // 3. Yahoo
        p(
            "yahoo",
            "Yahoo Mail",
            &[
                "yahoo.com",
                "yahoo.co.uk",
                "yahoo.co.jp",
                "yahoo.fr",
                "yahoo.de",
                "yahoo.it",
                "yahoo.es",
                "yahoo.com.br",
                "yahoo.com.au",
                "ymail.com",
                "rocketmail.com",
            ],
            &["*.yahoodns.net"],
            "imap.mail.yahoo.com",
            993,
            ssl,
            "smtp.mail.yahoo.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            Some("https://help.yahoo.com/kb/imap-server-settings-sln4075.html"),
            Some(OAuthConfig {
                auth_url: "https://api.login.yahoo.com/oauth2/request_auth".to_string(),
                token_url: "https://api.login.yahoo.com/oauth2/get_token".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec!["mail-w".to_string()],
                client_id: None,
                extra_params: vec![],
                userinfo_url: None,
            }),
            3,
        ),
        // 4. Apple iCloud
        p(
            "icloud",
            "iCloud Mail (Apple)",
            &["icloud.com", "me.com", "mac.com"],
            &["*.icloud.com"],
            "imap.mail.me.com",
            993,
            ssl,
            "smtp.mail.me.com",
            587,
            starttls,
            e,
            15,
            false,
            true,
            tls13,
            true,
            Some("https://support.apple.com/en-us/102525"),
            None,
            4,
        ),
        // 5. AOL
        p(
            "aol",
            "AOL Mail",
            &["aol.com", "aim.com", "netscape.net"],
            &["*.yahoodns.net"],
            "imap.aol.com",
            993,
            ssl,
            "smtp.aol.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            None,
            Some(OAuthConfig {
                auth_url: "https://api.login.aol.com/oauth2/request_auth".to_string(),
                token_url: "https://api.login.aol.com/oauth2/get_token".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec!["mail-w".to_string()],
                client_id: None,
                extra_params: vec![],
                userinfo_url: None,
            }),
            5,
        ),
        // 6. Mail.ru
        p(
            "mailru",
            "Mail.ru",
            &["mail.ru", "inbox.ru", "list.ru", "bk.ru", "internet.ru"],
            &["*.mail.ru"],
            "imap.mail.ru",
            993,
            ssl,
            "smtp.mail.ru",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            None,
            Some(OAuthConfig {
                auth_url: "https://oauth.mail.ru/login".to_string(),
                token_url: "https://oauth.mail.ru/token".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec!["mail.imap".to_string()],
                client_id: None,
                extra_params: vec![],
                userinfo_url: Some("https://oauth.mail.ru/userinfo".to_string()),
            }),
            6,
        ),
        // 7. Yandex
        p(
            "yandex",
            "Yandex Mail",
            &[
                "yandex.ru",
                "yandex.com",
                "yandex.ua",
                "yandex.by",
                "yandex.kz",
                "ya.ru",
                "narod.ru",
            ],
            &["*.yandex.ru"],
            "imap.yandex.com",
            993,
            ssl,
            "smtp.yandex.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            None,
            Some(OAuthConfig {
                auth_url: "https://oauth.yandex.com/authorize".to_string(),
                token_url: "https://oauth.yandex.com/token".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec!["mail:imap_full".to_string()],
                client_id: None,
                extra_params: vec![("force_confirm".to_string(), "true".to_string())],
                userinfo_url: None,
            }),
            7,
        ),
        // 8. Proton Mail
        p(
            "protonmail",
            "Proton Mail",
            &["protonmail.com", "proton.me", "pm.me", "protonmail.ch"],
            &[],
            "127.0.0.1",
            1143,
            starttls,
            "127.0.0.1",
            1025,
            starttls,
            e,
            15,
            false,
            false,
            tls13,
            false,
            Some("https://proton.me/support/protonmail-bridge-configure-client"),
            None,
            8,
        ),
        // 9. Zoho
        p(
            "zoho",
            "Zoho Mail",
            &["zoho.com", "zohomail.com", "zoho.eu", "zoho.in"],
            &["*.zoho.com"],
            "imap.zoho.com",
            993,
            ssl,
            "smtp.zoho.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            Some("https://www.zoho.com/mail/help/imap-access.html"),
            None,
            9,
        ),
        // 10. GMX
        p(
            "gmx",
            "GMX Mail",
            &["gmx.de", "gmx.net", "gmx.at", "gmx.ch", "gmx.com", "gmx.fr"],
            &["*.gmx.net"],
            "imap.gmx.net",
            993,
            ssl,
            "mail.gmx.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            10,
        ),
        // 11. Web.de
        p(
            "webde",
            "Web.de",
            &["web.de"],
            &["*.web.de"],
            "imap.web.de",
            993,
            ssl,
            "smtp.web.de",
            587,
            starttls,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            11,
        ),
        // 12. T-Online (Deutsche Telekom)
        p(
            "tonline",
            "T-Online",
            &["t-online.de", "magenta.de"],
            &["*.t-online.de"],
            "secureimap.t-online.de",
            993,
            ssl,
            "securesmtp.t-online.de",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            12,
        ),
        // 13. Office 365 (corporate)
        {
            let mut prov = p(
                "office365",
                "Microsoft 365",
                &["office365.com"],
                &["*.outlook.com", "*.protection.outlook.com"],
                "outlook.office365.com",
                993,
                ssl,
                "smtp.office365.com",
                587,
                starttls,
                e,
                15,
                false,
                true,
                tls13,
                false,
                None,
                Some(OAuthConfig {
                    auth_url: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize"
                        .to_string(),
                    token_url: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"
                        .to_string(),
                    redirect_uri: "http://127.0.0.1/callback".to_string(),
                    scopes: vec![
                        "https://outlook.office365.com/IMAP.AccessAsUser.All".to_string(),
                        "https://outlook.office365.com/SMTP.Send".to_string(),
                        "offline_access".to_string(),
                    ],
                    client_id: None,
                    extra_params: vec![("prompt".to_string(), "consent".to_string())],
                    userinfo_url: None,
                }),
                13,
            );
            prov.supports_shared_mailbox = true;
            prov
        },
        // 14. Comcast / Xfinity
        p(
            "comcast",
            "Comcast (Xfinity)",
            &["comcast.net", "xfinity.com"],
            &[],
            "imap.comcast.net",
            993,
            ssl,
            "smtp.comcast.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            14,
        ),
        // 15. Cox
        p(
            "cox",
            "Cox Communications",
            &["cox.net"],
            &[],
            "imap.cox.net",
            993,
            ssl,
            "smtp.cox.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            15,
        ),
        // 16. AT&T / SBCGlobal
        p(
            "att",
            "AT&T Mail",
            &[
                "att.net",
                "sbcglobal.net",
                "bellsouth.net",
                "pacbell.net",
                "ameritech.net",
                "flash.net",
            ],
            &[],
            "imap.mail.att.net",
            993,
            ssl,
            "smtp.mail.att.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            16,
        ),
        // 17. Verizon
        p(
            "verizon",
            "Verizon",
            &["verizon.net"],
            &[],
            "incoming.verizon.net",
            993,
            ssl,
            "smtp.verizon.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            17,
        ),
        // 18. QQ Mail
        p(
            "qq",
            "QQ Mail",
            &["qq.com", "foxmail.com"],
            &["*.qq.com"],
            "imap.qq.com",
            993,
            ssl,
            "smtp.qq.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            None,
            None,
            18,
        ),
        // 19. 163.com (NetEase)
        p(
            "163",
            "163 Mail (NetEase)",
            &["163.com", "126.com", "yeah.net"],
            &["*.163.com"],
            "imap.163.com",
            993,
            ssl,
            "smtp.163.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            true,
            None,
            Some(OAuthConfig {
                auth_url: "https://mail.163.com/oauth2/authorize".to_string(),
                token_url: "https://mail.163.com/oauth2/token".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec!["mail.imap".to_string()],
                client_id: None,
                extra_params: vec![],
                userinfo_url: None,
            }),
            19,
        ),
        // 20. Sina Mail
        p(
            "sina",
            "Sina Mail",
            &["sina.com", "sina.cn"],
            &[],
            "imap.sina.com",
            993,
            ssl,
            "smtp.sina.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            true,
            None,
            None,
            20,
        ),
        // === Regional and additional providers (21-160+) ===
        // Germany
        ssl_provider(
            "freenet",
            "Freenet",
            &["freenet.de"],
            "mx.freenet.de",
            "mx.freenet.de",
            21,
        ),
        ssl_provider(
            "posteo",
            "Posteo",
            &["posteo.de", "posteo.net", "posteo.eu"],
            "posteo.de",
            "posteo.de",
            22,
        ),
        ssl_provider(
            "mailbox_org",
            "Mailbox.org",
            &["mailbox.org"],
            "imap.mailbox.org",
            "smtp.mailbox.org",
            23,
        ),
        p(
            "ionos",
            "IONOS (1&1)",
            &["ionos.de", "online.de", "onlinehome.de"],
            &[],
            "imap.ionos.de",
            993,
            ssl,
            "smtp.ionos.de",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            24,
        ),
        ssl_provider(
            "arcor",
            "Arcor",
            &["arcor.de"],
            "imap.arcor.de",
            "mail.arcor.de",
            25,
        ),
        // France
        ssl_provider(
            "orange_fr",
            "Orange (France)",
            &["orange.fr", "wanadoo.fr", "voila.fr"],
            "imap.orange.fr",
            "smtp.orange.fr",
            26,
        ),
        p(
            "sfr",
            "SFR",
            &["sfr.fr", "neuf.fr", "club-internet.fr"],
            &[],
            "imap.sfr.fr",
            993,
            ssl,
            "smtp.sfr.fr",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            27,
        ),
        p(
            "free_fr",
            "Free (France)",
            &["free.fr", "aliceadsl.fr"],
            &[],
            "imap.free.fr",
            993,
            ssl,
            "smtp.free.fr",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            28,
        ),
        ssl_provider(
            "laposte",
            "La Poste",
            &["laposte.net"],
            "imap.laposte.net",
            "smtp.laposte.net",
            29,
        ),
        // Italy
        p(
            "libero",
            "Libero Mail",
            &["libero.it", "inwind.it", "iol.it", "blu.it"],
            &[],
            "imapmail.libero.it",
            993,
            ssl,
            "smtp.libero.it",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            30,
        ),
        ssl_provider(
            "tiscali_it",
            "Tiscali (Italy)",
            &["tiscali.it"],
            "imap.tiscali.it",
            "smtp.tiscali.it",
            31,
        ),
        ssl_provider(
            "virgilio",
            "Virgilio",
            &["virgilio.it"],
            "imap.virgilio.it",
            "smtp.virgilio.it",
            32,
        ),
        ssl_provider(
            "aruba_it",
            "Aruba (Italy)",
            &["aruba.it"],
            "imaps.aruba.it",
            "smtps.aruba.it",
            33,
        ),
        ssl_provider(
            "tim_it",
            "TIM Mail (Italy)",
            &["tim.it", "alice.it"],
            "imap.tim.it",
            "smtp.tim.it",
            34,
        ),
        // Spain
        ssl_provider(
            "telefonica",
            "Telefonica",
            &["telefonica.net", "movistar.es"],
            "imap.telefonica.net",
            "smtp.telefonica.net",
            35,
        ),
        // Netherlands
        ssl_provider(
            "ziggo",
            "Ziggo",
            &["ziggo.nl"],
            "imap.ziggo.nl",
            "smtp.ziggo.nl",
            36,
        ),
        ssl_provider(
            "kpn",
            "KPN Mail",
            &["kpnmail.nl", "planet.nl", "hetnet.nl"],
            "imap.kpnmail.nl",
            "smtp.kpnmail.nl",
            37,
        ),
        // UK
        ssl_provider(
            "btinternet",
            "BT Internet",
            &["btinternet.com", "btopenworld.com"],
            "mail.btinternet.com",
            "mail.btinternet.com",
            38,
        ),
        ssl_provider(
            "sky_uk",
            "Sky (UK)",
            &["sky.com"],
            "imap.tools.sky.com",
            "smtp.tools.sky.com",
            39,
        ),
        ssl_provider(
            "talktalk",
            "TalkTalk",
            &["talktalk.net", "tiscali.co.uk"],
            "imap.talktalk.net",
            "smtp.talktalk.net",
            40,
        ),
        ssl_provider(
            "virginmedia",
            "Virgin Media",
            &["virginmedia.com", "ntlworld.com", "blueyonder.co.uk"],
            "imap.virginmedia.com",
            "smtp.virginmedia.com",
            41,
        ),
        // Scandinavia
        ssl_provider(
            "telia_se",
            "Telia (Sweden)",
            &["telia.com"],
            "mail.telia.com",
            "mail.telia.com",
            42,
        ),
        ssl_provider(
            "bredband",
            "Bredbandsbolaget",
            &["bredband.net"],
            "imap.bredband.net",
            "smtp.bredband.net",
            43,
        ),
        ssl_provider(
            "telenor_no",
            "Telenor (Norway)",
            &["telenor.no", "online.no"],
            "imap.telenor.no",
            "smtp.telenor.no",
            44,
        ),
        ssl_provider(
            "tele2",
            "Tele2",
            &["tele2.se", "tele2.nl"],
            "imap.tele2.se",
            "smtp.tele2.se",
            45,
        ),
        // Russia / CIS
        ssl_provider(
            "rambler",
            "Rambler",
            &[
                "rambler.ru",
                "lenta.ru",
                "autorambler.ru",
                "myrambler.ru",
                "ro.ru",
            ],
            "imap.rambler.ru",
            "smtp.rambler.ru",
            46,
        ),
        ssl_provider(
            "ukr_net",
            "UKR.NET",
            &["ukr.net"],
            "imap.ukr.net",
            "smtp.ukr.net",
            47,
        ),
        ssl_provider("i_ua", "I.UA", &["i.ua"], "imap.i.ua", "smtp.i.ua", 48),
        ssl_provider(
            "meta_ua",
            "Meta.ua",
            &["meta.ua"],
            "imap.meta.ua",
            "smtp.meta.ua",
            49,
        ),
        // Japan
        p(
            "nifty",
            "Nifty",
            &["nifty.com"],
            &[],
            "imap.nifty.com",
            993,
            ssl,
            "smtp.nifty.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            50,
        ),
        p(
            "biglobe",
            "BIGLOBE",
            &["biglobe.ne.jp"],
            &[],
            "mail.biglobe.ne.jp",
            993,
            ssl,
            "mail.biglobe.ne.jp",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            51,
        ),
        p(
            "ocn",
            "OCN",
            &["ocn.ne.jp"],
            &[],
            "imap.ocn.ne.jp",
            993,
            ssl,
            "smtp.ocn.ne.jp",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            52,
        ),
        p(
            "so_net",
            "So-net",
            &["so-net.ne.jp"],
            &[],
            "imap.so-net.ne.jp",
            993,
            ssl,
            "smtp.so-net.ne.jp",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            53,
        ),
        // South Korea
        p(
            "naver",
            "Naver Mail",
            &["naver.com"],
            &[],
            "imap.naver.com",
            993,
            ssl,
            "smtp.naver.com",
            587,
            starttls,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            54,
        ),
        p(
            "daum",
            "Daum / Kakao Mail",
            &["daum.net", "hanmail.net", "kakao.com"],
            &[],
            "imap.daum.net",
            993,
            ssl,
            "smtp.daum.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            55,
        ),
        // India
        p(
            "rediffmail",
            "Rediffmail",
            &["rediffmail.com", "rediff.com"],
            &[],
            "imap.rediffmail.com",
            993,
            ssl,
            "smtp.rediffmail.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            56,
        ),
        // Brazil
        p(
            "uol",
            "UOL Mail",
            &["uol.com.br", "bol.com.br"],
            &[],
            "imap.uol.com.br",
            993,
            ssl,
            "smtps.uol.com.br",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            57,
        ),
        p(
            "terra_br",
            "Terra (Brazil)",
            &["terra.com.br"],
            &[],
            "imap.terra.com.br",
            993,
            ssl,
            "smtp.terra.com.br",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            58,
        ),
        p(
            "ig",
            "iG Mail",
            &["ig.com.br"],
            &[],
            "imap.ig.com.br",
            993,
            ssl,
            "smtp.ig.com.br",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            59,
        ),
        // Australia
        ssl_provider(
            "optus",
            "Optus",
            &["optusnet.com.au"],
            "mail.optusnet.com.au",
            "mail.optusnet.com.au",
            60,
        ),
        ssl_provider(
            "bigpond",
            "Bigpond (Telstra)",
            &["bigpond.com", "bigpond.net.au", "telstra.com"],
            "imap.telstra.com",
            "smtp.telstra.com",
            61,
        ),
        ssl_provider(
            "iinet",
            "iiNet",
            &["iinet.net.au"],
            "mail.iinet.net.au",
            "mail.iinet.net.au",
            62,
        ),
        // Canada
        ssl_provider(
            "shaw",
            "Shaw",
            &["shaw.ca"],
            "imap.shaw.ca",
            "smtp.shaw.ca",
            63,
        ),
        ssl_provider(
            "rogers",
            "Rogers",
            &["rogers.com"],
            "imap.rogers.com",
            "smtp.rogers.com",
            64,
        ),
        ssl_provider(
            "bell_ca",
            "Bell Canada",
            &["bell.net", "sympatico.ca"],
            "imap.bell.net",
            "smtp.bell.net",
            65,
        ),
        // Privacy-focused
        ssl_provider(
            "tutanota",
            "Tutanota",
            &[
                "tutanota.com",
                "tutanota.de",
                "tuta.io",
                "tutamail.com",
                "keemail.me",
            ],
            "imap.tutanota.com",
            "smtp.tutanota.com",
            66,
        ),
        p(
            "fastmail",
            "Fastmail",
            &["fastmail.com", "fastmail.fm", "messagingengine.com"],
            &[],
            "imap.fastmail.com",
            993,
            ssl,
            "smtp.fastmail.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            Some(OAuthConfig {
                auth_url: "https://api.fastmail.com/oauth/authorize".to_string(),
                token_url: "https://api.fastmail.com/oauth/refresh".to_string(),
                redirect_uri: "http://127.0.0.1/callback".to_string(),
                scopes: vec![
                    "urn:ietf:params:jmap:mail".to_string(),
                    "urn:ietf:params:jmap:submission".to_string(),
                ],
                client_id: None,
                extra_params: vec![],
                userinfo_url: None,
            }),
            67,
        ),
        ssl_provider(
            "runbox",
            "Runbox",
            &["runbox.com"],
            "mail.runbox.com",
            "mail.runbox.com",
            68,
        ),
        ssl_provider(
            "mailfence",
            "Mailfence",
            &["mailfence.com"],
            "imap.mailfence.com",
            "smtp.mailfence.com",
            69,
        ),
        ssl_provider(
            "disroot",
            "Disroot",
            &["disroot.org"],
            "disroot.org",
            "disroot.org",
            70,
        ),
        ssl_provider(
            "riseup",
            "Riseup",
            &["riseup.net"],
            "mail.riseup.net",
            "mail.riseup.net",
            71,
        ),
        ssl_provider(
            "kolab",
            "Kolab Now",
            &["kolabnow.com", "mykolab.com"],
            "imap.kolabnow.com",
            "smtp.kolabnow.com",
            72,
        ),
        ssl_provider(
            "autistici",
            "Autistici",
            &["autistici.org", "inventati.org"],
            "mail.autistici.org",
            "smtp.autistici.org",
            73,
        ),
        // Hosting providers
        ssl_provider(
            "namecheap",
            "Namecheap Email",
            &["privateemail.com"],
            "mail.privateemail.com",
            "mail.privateemail.com",
            74,
        ),
        ssl_provider(
            "gandi",
            "Gandi Mail",
            &["gandi.net"],
            "mail.gandi.net",
            "mail.gandi.net",
            75,
        ),
        ssl_provider(
            "hover",
            "Hover",
            &["hover.com"],
            "mail.hover.com",
            "mail.hover.com",
            76,
        ),
        ssl_provider(
            "migadu",
            "Migadu",
            &["migadu.com"],
            "imap.migadu.com",
            "smtp.migadu.com",
            77,
        ),
        ssl_provider(
            "mxroute",
            "MXroute",
            &["mxroute.com"],
            "imap.mxroute.com",
            "smtp.mxroute.com",
            78,
        ),
        // Poland
        ssl_provider(
            "wp_pl",
            "WP.pl (Wirtualna Polska)",
            &["wp.pl"],
            "imap.wp.pl",
            "smtp.wp.pl",
            79,
        ),
        ssl_provider(
            "onet_pl",
            "Onet.pl",
            &["onet.pl", "onet.eu", "op.pl", "vp.pl", "poczta.onet.pl"],
            "imap.poczta.onet.pl",
            "smtp.poczta.onet.pl",
            80,
        ),
        ssl_provider(
            "interia_pl",
            "Interia.pl",
            &["interia.pl", "interia.eu", "poczta.fm"],
            "imap.interia.pl",
            "smtp.interia.pl",
            81,
        ),
        ssl_provider(
            "o2_pl",
            "O2.pl",
            &["o2.pl", "tlen.pl"],
            "poczta.o2.pl",
            "poczta.o2.pl",
            82,
        ),
        // Czech Republic
        ssl_provider(
            "seznam",
            "Seznam.cz",
            &["seznam.cz", "email.cz", "post.cz", "spoluzaci.cz"],
            "imap.seznam.cz",
            "smtp.seznam.cz",
            83,
        ),
        ssl_provider(
            "centrum_cz",
            "Centrum.cz",
            &["centrum.cz", "centrum.sk"],
            "imap.centrum.cz",
            "smtp.centrum.cz",
            84,
        ),
        // Turkey
        ssl_provider(
            "yandex_tr",
            "Yandex (Turkey)",
            &["yandex.com.tr"],
            "imap.yandex.com.tr",
            "smtp.yandex.com.tr",
            85,
        ),
        // Portugal
        ssl_provider(
            "sapo",
            "SAPO Mail",
            &["sapo.pt"],
            "imap.sapo.pt",
            "smtp.sapo.pt",
            86,
        ),
        // Switzerland
        ssl_provider(
            "bluewin",
            "Bluewin (Swisscom)",
            &["bluewin.ch"],
            "imaps.bluewin.ch",
            "smtps.bluewin.ch",
            87,
        ),
        ssl_provider(
            "gmx_ch",
            "GMX.ch",
            &["gmx.ch"],
            "imap.gmx.ch",
            "mail.gmx.ch",
            88,
        ),
        // Austria
        ssl_provider(
            "a1_at",
            "A1 (Austria)",
            &["a1.net", "aon.at"],
            "imap.a1.net",
            "smtp.a1.net",
            89,
        ),
        ssl_provider(
            "chello_at",
            "Chello (Austria)",
            &["chello.at"],
            "imap.chello.at",
            "smtp.chello.at",
            90,
        ),
        // Belgium
        ssl_provider(
            "telenet_be",
            "Telenet (Belgium)",
            &["telenet.be"],
            "imap.telenet.be",
            "smtp.telenet.be",
            91,
        ),
        ssl_provider(
            "skynet_be",
            "Skynet (Proximus)",
            &["skynet.be", "proximus.be"],
            "imap.skynet.be",
            "smtp.skynet.be",
            92,
        ),
        // China
        p(
            "sohu",
            "Sohu Mail",
            &["sohu.com"],
            &[],
            "imap.sohu.com",
            993,
            ssl,
            "smtp.sohu.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            true,
            None,
            None,
            93,
        ),
        p(
            "aliyun",
            "Aliyun Mail",
            &["aliyun.com"],
            &[],
            "imap.aliyun.com",
            993,
            ssl,
            "smtp.aliyun.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            94,
        ),
        p(
            "tom",
            "Tom.com",
            &["tom.com"],
            &[],
            "imap.tom.com",
            993,
            ssl,
            "smtp.tom.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            95,
        ),
        p(
            "_21cn",
            "21CN",
            &["21cn.com"],
            &[],
            "imap.21cn.com",
            993,
            ssl,
            "smtp.21cn.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            true,
            None,
            None,
            96,
        ),
        // Taiwan
        p(
            "hinet",
            "HiNet",
            &["hinet.net"],
            &[],
            "msa.hinet.net",
            993,
            ssl,
            "msa.hinet.net",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            false,
            None,
            None,
            97,
        ),
        // Southeast Asia
        ssl_provider(
            "singnet",
            "SingNet",
            &["singnet.com.sg"],
            "imap.singnet.com.sg",
            "smtp.singnet.com.sg",
            98,
        ),
        ssl_provider(
            "tm_net",
            "TM Net (Malaysia)",
            &["tm.net.my", "streamyx.com"],
            "imap.tm.net.my",
            "smtp.tm.net.my",
            99,
        ),
        // Mexico
        ssl_provider(
            "prodigy",
            "Prodigy (Telmex)",
            &["prodigy.net.mx"],
            "imap.prodigy.net.mx",
            "smtp.prodigy.net.mx",
            100,
        ),
        // Argentina
        ssl_provider(
            "fibertel",
            "Fibertel",
            &["fibertel.com.ar"],
            "imap.fibertel.com.ar",
            "smtp.fibertel.com.ar",
            101,
        ),
        ssl_provider(
            "arnet",
            "Arnet",
            &["arnet.com.ar"],
            "imap.arnet.com.ar",
            "smtp.arnet.com.ar",
            102,
        ),
        // South Africa
        ssl_provider(
            "mweb",
            "MWEB",
            &["mweb.co.za"],
            "imap.mweb.co.za",
            "smtp.mweb.co.za",
            103,
        ),
        ssl_provider(
            "webmail_co_za",
            "Web Mail (ZA)",
            &["webmail.co.za"],
            "imap.webmail.co.za",
            "smtp.webmail.co.za",
            104,
        ),
        // Middle East
        ssl_provider(
            "emirates",
            "Emirates (UAE)",
            &["emirates.net.ae"],
            "imap.emirates.net.ae",
            "smtp.emirates.net.ae",
            105,
        ),
        // Greece
        ssl_provider(
            "otenet",
            "OTEnet (Greece)",
            &["otenet.gr"],
            "imap.otenet.gr",
            "smtp.otenet.gr",
            106,
        ),
        ssl_provider(
            "forthnet",
            "Forthnet (Greece)",
            &["forthnet.gr"],
            "imap.forthnet.gr",
            "smtp.forthnet.gr",
            107,
        ),
        // Hungary
        ssl_provider(
            "freemail_hu",
            "Freemail.hu",
            &["freemail.hu", "citromail.hu"],
            "imap.freemail.hu",
            "smtp.freemail.hu",
            108,
        ),
        ssl_provider(
            "t_online_hu",
            "T-Online Hungary",
            &["t-online.hu"],
            "imap.t-online.hu",
            "smtp.t-online.hu",
            109,
        ),
        // Romania
        ssl_provider(
            "rdslink",
            "RDS (Romania)",
            &["rdslink.ro", "rds.ro"],
            "imap.rdslink.ro",
            "smtp.rdslink.ro",
            110,
        ),
        // Finland
        ssl_provider(
            "elisa_fi",
            "Elisa (Finland)",
            &["elisa.fi", "kolumbus.fi", "saunalahti.fi"],
            "imap.elisa.fi",
            "smtp.elisa.fi",
            111,
        ),
        ssl_provider(
            "pp_fi",
            "PP (Finland)",
            &["pp.inet.fi", "luukku.com"],
            "imap.pp.inet.fi",
            "smtp.pp.inet.fi",
            112,
        ),
        // Denmark
        ssl_provider(
            "jubii",
            "Jubii",
            &["jubii.dk"],
            "imap.jubii.dk",
            "smtp.jubii.dk",
            113,
        ),
        ssl_provider(
            "tdcadsl",
            "TDC",
            &["tdcadsl.dk", "tdc.dk"],
            "imap.mail.dk",
            "smtp.mail.dk",
            114,
        ),
        // Norway
        ssl_provider(
            "start_no",
            "Start.no",
            &["start.no"],
            "imap.start.no",
            "smtp.start.no",
            115,
        ),
        // New Zealand
        ssl_provider(
            "xtra",
            "Xtra (NZ)",
            &["xtra.co.nz"],
            "imap.xtra.co.nz",
            "smtp.xtra.co.nz",
            116,
        ),
        ssl_provider(
            "vodafone_nz",
            "Vodafone NZ",
            &["vodafone.co.nz"],
            "imap.vodafone.co.nz",
            "smtp.vodafone.co.nz",
            117,
        ),
        // Generic / Open-source hosting
        ssl_provider(
            "soverin",
            "Soverin",
            &["soverin.net"],
            "imap.soverin.net",
            "smtp.soverin.net",
            118,
        ),
        ssl_provider(
            "countermail",
            "CounterMail",
            &["countermail.com"],
            "imap.countermail.com",
            "smtp.countermail.com",
            119,
        ),
        ssl_provider(
            "ctemplar",
            "CTemplar",
            &["ctemplar.com"],
            "imap.ctemplar.com",
            "smtp.ctemplar.com",
            120,
        ),
        // Education (generic patterns)
        p(
            "edu_google",
            "Google Workspace (Education)",
            &["*.edu"],
            &["*.google.com", "*.googlemail.com"],
            "imap.gmail.com",
            993,
            ssl,
            "smtp.gmail.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls13,
            false,
            None,
            None,
            121,
        ),
        // More ISPs
        ssl_provider(
            "charter",
            "Charter / Spectrum",
            &["charter.net", "roadrunner.com", "rr.com"],
            "mobile.charter.net",
            "mobile.charter.net",
            122,
        ),
        ssl_provider(
            "centurylink",
            "CenturyLink",
            &["centurylink.net", "centurytel.net", "embarqmail.com"],
            "imap.centurylink.net",
            "smtp.centurylink.net",
            123,
        ),
        ssl_provider(
            "earthlink",
            "EarthLink",
            &["earthlink.net", "mindspring.com"],
            "imap.earthlink.net",
            "smtp.earthlink.net",
            124,
        ),
        ssl_provider(
            "windstream",
            "Windstream",
            &["windstream.net"],
            "imap.windstream.net",
            "smtp.windstream.net",
            125,
        ),
        ssl_provider(
            "frontier",
            "Frontier",
            &["frontier.com", "frontiernet.net"],
            "imap.frontier.com",
            "smtp.frontier.com",
            126,
        ),
        // Additional international
        ssl_provider(
            "mail_com",
            "Mail.com",
            &[
                "mail.com",
                "email.com",
                "usa.com",
                "consultant.com",
                "europe.com",
                "asia.com",
            ],
            "imap.mail.com",
            "smtp.mail.com",
            127,
        ),
        ssl_provider(
            "inbox_lv",
            "Inbox.lv",
            &["inbox.lv"],
            "imap.inbox.lv",
            "smtp.inbox.lv",
            128,
        ),
        ssl_provider(
            "one_com",
            "One.com",
            &["one.com"],
            "imap.one.com",
            "send.one.com",
            129,
        ),
        ssl_provider(
            "strato",
            "Strato",
            &["strato.de"],
            "imap.strato.de",
            "smtp.strato.de",
            130,
        ),
        ssl_provider(
            "mailbox_hu",
            "Mailbox.hu",
            &["mailbox.hu"],
            "imap.mailbox.hu",
            "smtp.mailbox.hu",
            131,
        ),
        ssl_provider(
            "azet_sk",
            "Azet.sk",
            &["azet.sk", "centrum.sk"],
            "imap.azet.sk",
            "smtp.azet.sk",
            132,
        ),
        ssl_provider(
            "abv_bg",
            "ABV.bg",
            &["abv.bg", "gyuvetch.bg"],
            "imap.abv.bg",
            "smtp.abv.bg",
            133,
        ),
        ssl_provider(
            "dir_bg",
            "Dir.bg",
            &["dir.bg"],
            "imap.dir.bg",
            "smtp.dir.bg",
            134,
        ),
        ssl_provider(
            "walla",
            "Walla (Israel)",
            &["walla.co.il", "walla.com"],
            "imap.walla.co.il",
            "smtp.walla.co.il",
            135,
        ),
        ssl_provider(
            "bezeqint",
            "Bezeq (Israel)",
            &["bezeqint.net", "013.net"],
            "imap.bezeqint.net",
            "smtp.bezeqint.net",
            136,
        ),
        // Africa
        ssl_provider(
            "africa_online",
            "Africa Online",
            &["africaonline.com"],
            "imap.africaonline.com",
            "smtp.africaonline.com",
            137,
        ),
        ssl_provider(
            "webmail_ng",
            "Webmail.ng (Nigeria)",
            &["webmail.ng"],
            "imap.webmail.ng",
            "smtp.webmail.ng",
            138,
        ),
        // More Asia
        p(
            "139mail",
            "139 Mail (China Mobile)",
            &["139.com"],
            &[],
            "imap.139.com",
            993,
            ssl,
            "smtp.139.com",
            465,
            ssl,
            e,
            15,
            false,
            true,
            tls12,
            true,
            None,
            None,
            139,
        ),
        ssl_provider(
            "nate",
            "Nate (South Korea)",
            &["nate.com", "empal.com"],
            "imap.nate.com",
            "smtp.nate.com",
            140,
        ),
        ssl_provider(
            "plala",
            "Plala (Japan)",
            &["plala.or.jp"],
            "imap.plala.or.jp",
            "smtp.plala.or.jp",
            141,
        ),
        ssl_provider(
            "excite_jp",
            "Excite Japan",
            &["excite.co.jp"],
            "imap.excite.co.jp",
            "smtp.excite.co.jp",
            142,
        ),
        // More European
        ssl_provider(
            "tin_it",
            "TIN.it",
            &["tin.it"],
            "imap.tin.it",
            "smtp.tin.it",
            143,
        ),
        ssl_provider(
            "email_it",
            "Email.it",
            &["email.it"],
            "imap.email.it",
            "smtp.email.it",
            144,
        ),
        ssl_provider(
            "lycos",
            "Lycos Mail",
            &["lycos.com", "lycos.de", "lycos.co.uk"],
            "imap.lycos.com",
            "smtp.lycos.com",
            145,
        ),
        ssl_provider(
            "netcologne",
            "NetCologne",
            &["netcologne.de"],
            "imap.netcologne.de",
            "smtp.netcologne.de",
            146,
        ),
        ssl_provider(
            "versatel",
            "Versatel",
            &["versatel.de"],
            "imap.versatel.de",
            "smtp.versatel.de",
            147,
        ),
        ssl_provider(
            "vodafone_de",
            "Vodafone Germany",
            &["vodafone.de", "arcor.de", "kabelmail.de"],
            "imap.vodafone.de",
            "smtp.vodafone.de",
            148,
        ),
        ssl_provider(
            "hispeed_ch",
            "Hispeed.ch",
            &["hispeed.ch"],
            "imap.hispeed.ch",
            "smtp.hispeed.ch",
            149,
        ),
        ssl_provider(
            "sunrise_ch",
            "Sunrise (Switzerland)",
            &["sunrise.ch"],
            "imap.sunrise.ch",
            "smtp.sunrise.ch",
            150,
        ),
        // Additional global
        ssl_provider(
            "aim_mail",
            "AIM Mail",
            &["aim.com"],
            "imap.aim.com",
            "smtp.aim.com",
            151,
        ),
        ssl_provider(
            "safe_mail",
            "Safe-mail",
            &["safe-mail.net"],
            "imap.safe-mail.net",
            "smtp.safe-mail.net",
            152,
        ),
        ssl_provider(
            "hushmail",
            "Hushmail",
            &["hushmail.com", "hush.com", "hush.ai"],
            "imap.hushmail.com",
            "smtp.hushmail.com",
            153,
        ),
        ssl_provider(
            "startmail",
            "StartMail",
            &["startmail.com"],
            "imap.startmail.com",
            "smtp.startmail.com",
            154,
        ),
        ssl_provider(
            "eclipso",
            "Eclipso",
            &["eclipso.de", "eclipso.eu", "eclipso.at"],
            "imap.eclipso.de",
            "smtp.eclipso.de",
            155,
        ),
        ssl_provider(
            "mail_de",
            "Mail.de",
            &["mail.de"],
            "imap.mail.de",
            "smtp.mail.de",
            156,
        ),
        ssl_provider(
            "emailn_de",
            "Emailn.de",
            &["emailn.de"],
            "imap.emailn.de",
            "smtp.emailn.de",
            157,
        ),
        ssl_provider(
            "inbox_com",
            "Inbox.com",
            &["inbox.com"],
            "imap.inbox.com",
            "smtp.inbox.com",
            158,
        ),
        ssl_provider(
            "lavabit",
            "Lavabit",
            &["lavabit.com"],
            "imap.lavabit.com",
            "smtp.lavabit.com",
            159,
        ),
        ssl_provider(
            "tuta_com",
            "Tuta.com",
            &["tuta.com"],
            "imap.tuta.com",
            "smtp.tuta.com",
            160,
        ),
    ]
}
